/**
 * Stripe Payment Method Configurations as per-order invoice presets.
 *
 * WHY THIS EXISTS — the Invoices API does not accept a `pmc_` id. On stripe-node 20
 * (API `2025-12-15.clover`) only Checkout Sessions, PaymentIntents, SetupIntents and
 * Billing Portal Configurations take `payment_method_configuration`. Invoice
 * `payment_settings` takes `default_mandate`, `payment_method_options` and
 * `payment_method_types` — nothing else.
 *
 * So a configuration is used here as the SOURCE OF TRUTH for a method list, not as a
 * value handed to Stripe: retrieve the config, read which methods it turns on, and
 * pass those as the invoice's `payment_method_types`. The Dashboard stays the place
 * you edit what a preset means; the code just reads it.
 *
 * Two filters are not optional, both learned from the live account:
 *
 *  1. `available === true`. The default configuration on this account lists `affirm`,
 *     `blik` and `giropay` as ON while all three are unavailable (not enabled on the
 *     account). Forwarding an unavailable method fails invoice creation.
 *  2. Membership in the invoice `payment_method_types` union. A configuration exposes
 *     54 method keys; invoices accept 40, and 19 config keys have no invoice
 *     equivalent at all — `apple_pay`, `google_pay`, `samsung_pay` and
 *     `cartes_bancaires` ride on `card`, and the rest simply are not invoice-payable.
 *
 * Note that a configuration's own `active` flag is deliberately ignored. It governs
 * whether STRIPE may use the config directly; we only read it, so an inactive config
 * is still a perfectly good preset. (The card-enabling config on this account is
 * inactive, which is exactly the case that matters.)
 */

import type Stripe from 'stripe'
import { getStripe } from '@/lib/stripe'

/**
 * Every value the invoice `payment_settings.payment_method_types` union accepts that a
 * payment method configuration can also turn on. Generated by intersecting
 * `Stripe.InvoiceCreateParams.PaymentSettings.PaymentMethodType` with the
 * `Stripe.PaymentMethodConfiguration` method keys — regenerate after a Stripe upgrade.
 *
 * Deliberately excluded because no configuration key maps to them: `ach_credit_transfer`,
 * `ach_debit`, `custom`, `jp_credit_transfer`, `sepa_credit_transfer`.
 */
const INVOICE_PAYABLE_METHODS = new Set<string>([
  'acss_debit',
  'affirm',
  'amazon_pay',
  'au_becs_debit',
  'bacs_debit',
  'bancontact',
  'boleto',
  'card',
  'cashapp',
  'crypto',
  'customer_balance',
  'eps',
  'fpx',
  'giropay',
  'grabpay',
  'ideal',
  'kakao_pay',
  'klarna',
  'konbini',
  'kr_card',
  'link',
  'multibanco',
  'naver_pay',
  'nz_bank_account',
  'payco',
  'paynow',
  'paypal',
  'payto',
  'promptpay',
  'revolut_pay',
  'sepa_debit',
  'sofort',
  'swish',
  'us_bank_account',
  'wechat_pay',
])

/** Top-level fields on a configuration that are metadata, not payment methods. */
const NON_METHOD_KEYS = new Set([
  'id',
  'object',
  'active',
  'application',
  'is_default',
  'livemode',
  'name',
  'parent',
])

type InvoicePaymentMethodType = NonNullable<
  Stripe.InvoiceCreateParams.PaymentSettings['payment_method_types']
> extends Array<infer T>
  ? T
  : never

export interface PaymentConfigOption {
  id: string
  name: string
  /** Stripe's own default configuration for the account. */
  isDefault: boolean
  /**
   * The configuration's `active` flag. Shown for context only — an inactive config is
   * still usable as a preset here, because its id is never sent to Stripe.
   */
  active: boolean
  /** Invoice-payable methods this config turns on, after both filters. */
  methods: string[]
  /** True when `card` survives the filters — the thing staff actually care about. */
  allowsCard: boolean
}

// ── Cache ─────────────────────────────────────────────────────────────────────
// A configuration changes when somebody edits it in the Dashboard, which is rare, and
// a stale read only means an invoice offers last hour's method list. Worth far more
// than a Stripe round-trip on the critical path of every invoice.
const TTL_MS = 5 * 60 * 1000
let listCache: { at: number; options: PaymentConfigOption[] } | null = null
const methodCache = new Map<string, { at: number; methods: InvoicePaymentMethodType[] }>()

const fresh = (at: number) => Date.now() - at < TTL_MS

/** Read the invoice-payable methods a configuration object turns on. */
function invoiceMethodsOf(config: Stripe.PaymentMethodConfiguration): InvoicePaymentMethodType[] {
  const methods: string[] = []

  for (const [key, value] of Object.entries(config)) {
    if (NON_METHOD_KEYS.has(key)) continue
    if (!value || typeof value !== 'object') continue

    const entry = value as {
      available?: boolean
      display_preference?: { value?: string }
    }
    // Both filters — see the file header for why each one is load-bearing.
    if (entry.display_preference?.value !== 'on') continue
    if (entry.available !== true) continue
    if (!INVOICE_PAYABLE_METHODS.has(key)) continue

    methods.push(key)
  }

  return methods.sort() as InvoicePaymentMethodType[]
}

/**
 * Every payment method configuration on the account, as selectable presets.
 *
 * Not filtered by `active` — see the file header. Cached for five minutes; pass
 * `{ refresh: true }` after editing a configuration in the Dashboard.
 */
export async function listPaymentConfigs(
  opts: { refresh?: boolean; stripe?: Stripe } = {},
): Promise<PaymentConfigOption[]> {
  if (!opts.refresh && listCache && fresh(listCache.at)) return listCache.options

  const stripe = opts.stripe ?? getStripe()
  const { data } = await stripe.paymentMethodConfigurations.list({ limit: 100 })

  const options = data.map((config) => {
    const methods = invoiceMethodsOf(config)
    // Warm the per-id cache for free — resolving one for an invoice is now a local read.
    methodCache.set(config.id, { at: Date.now(), methods })
    return {
      id: config.id,
      name: config.name,
      isDefault: config.is_default,
      active: config.active,
      methods,
      allowsCard: methods.includes('card' as InvoicePaymentMethodType),
    }
  })

  listCache = { at: Date.now(), options }
  return options
}

/**
 * The invoice `payment_settings` a configuration implies, or `undefined`.
 *
 * `undefined` means "send no payment_settings", which is meaningfully different from
 * an empty list: with the field omitted Stripe falls back to the invoice's default
 * payment method, then the customer's, then the account's invoice template settings.
 * An empty array would instead be an explicit "no methods" and fail the invoice. So
 * an unknown id, an unreachable Stripe, or a configuration whose every method is
 * unavailable all degrade to the account default rather than to a broken invoice.
 */
export async function invoicePaymentSettingsFor(
  paymentConfigId: string | null | undefined,
  opts: { stripe?: Stripe } = {},
): Promise<Stripe.InvoiceCreateParams.PaymentSettings | undefined> {
  const methods = await invoiceMethodsForConfig(paymentConfigId, opts)
  if (!methods || methods.length === 0) return undefined
  return { payment_method_types: methods }
}

/** The filtered method list for one configuration, cached. `null` when unresolvable. */
export async function invoiceMethodsForConfig(
  paymentConfigId: string | null | undefined,
  opts: { stripe?: Stripe } = {},
): Promise<InvoicePaymentMethodType[] | null> {
  if (!paymentConfigId) return null

  const cached = methodCache.get(paymentConfigId)
  if (cached && fresh(cached.at)) return cached.methods

  try {
    const stripe = opts.stripe ?? getStripe()
    const config = await stripe.paymentMethodConfigurations.retrieve(paymentConfigId)
    const methods = invoiceMethodsOf(config)
    methodCache.set(paymentConfigId, { at: Date.now(), methods })
    return methods
  } catch (e) {
    // Never fail an invoice over a preset lookup — fall back to the account default.
    console.error(
      `[paymentConfigs] Could not resolve ${paymentConfigId}; invoicing with the account default instead:`,
      e,
    )
    return null
  }
}

/** Display name for a configuration id, for stamping onto the order. Never throws. */
export async function paymentConfigNameFor(
  paymentConfigId: string | null | undefined,
): Promise<string | null> {
  if (!paymentConfigId) return null
  try {
    const options = await listPaymentConfigs()
    return options.find((o) => o.id === paymentConfigId)?.name ?? null
  } catch {
    return null
  }
}

/**
 * Which configuration an invoice should use, most specific wins:
 *
 *   explicit per-order choice → the client account's standing default → env default → none
 *
 * `none` hands Stripe nothing and lets its own invoice template settings decide, which
 * is what every package and client-order flow did before this existed.
 */
export function resolvePaymentConfigId(sources: {
  /** Chosen in the order-creation UI for this one invoice. */
  explicit?: string | null
  /** `ClientAccounts.defaultPaymentConfig` — e.g. a client who always pays by card. */
  clientAccountDefault?: string | null
}): string | null {
  return (
    sources.explicit?.trim() ||
    sources.clientAccountDefault?.trim() ||
    process.env.STRIPE_DEFAULT_PAYMENT_CONFIG?.trim() ||
    null
  )
}

/**
 * Resolve the configuration for one invoice and snapshot its name, in one call.
 *
 * What every order-creation flow needs: run the precedence chain, then record both the
 * id and the human name on the order so the admin view reads without hitting Stripe.
 * Never throws — an unresolvable preset degrades to the account default.
 */
export async function prepareInvoicePaymentConfig(sources: {
  explicit?: string | null
  clientAccountDefault?: string | null
}): Promise<{ id: string | null; name: string | null }> {
  const id = resolvePaymentConfigId(sources)
  if (!id) return { id: null, name: null }
  return { id, name: await paymentConfigNameFor(id) }
}
