version: '3.8'

# Production-ready Docker Compose for OrcaClubPro
# Next.js + Payload CMS + SQLite with Bun runtime

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
      target: runner
    container_name: orcaclubpro-app
    restart: unless-stopped
    
    ports:
      - "${PORT:-3000}:3000"
    
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URI=${DATABASE_URI:-file:./data/payload.db}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET:-your-secret-key-change-this}
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    
    volumes:
      # Persist database data
      - db_data:/app/data
      # Optional: Mount local database for development
      # - ./payload.db:/app/data/payload.db
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Prevent container from running as root
    user: "1001:1001"

volumes:
  db_data:
    driver: local 