# nixpacks.toml configuration for Bun-based Next.js project

# Use node provider but override with bun
providers = ["node"]

[phases.setup]
# Ensure bun and build tools are available
nixPkgs = ["bun", "nodejs", "python3", "gcc", "gnumake", "pkg-config"]

[phases.install]
# Use bun install and rebuild native modules
cmds = [
  "bun install --no-frozen-lockfile",
  "npm rebuild better-sqlite3 --build-from-source"
]

[phases.build] 
# Use your build command that runs payload build and next build
cmds = ["bun run build"]

[start]
# Use your start command
cmd = "bun run start"

# Environment variables
[variables]
NODE_ENV = "production"
# Ensure proper node-gyp environment
npm_config_cache = "/tmp/.npm"
npm_config_build_from_source = "true"