# nixpacks.toml configuration for Bun-based Next.js project

# Use node provider but override with bun
providers = ["node"]

[phases.setup]
# Ensure bun is available
nixPkgs = ["bun"]

[phases.install]
# Use bun install to install dependencies
cmds = ["bun install --frozen-lockfile"]

[phases.build] 
# Use your build command that runs payload build and next build
cmds = ["bun run build"]

[start]
# Use your start command
cmd = "bun run start"

# Environment variables
[variables]
NODE_ENV = "production"