/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    clients: Client;
    leads: Lead;
    categories: Category;
    tags: Tag;
    posts: Post;
    solutions: Solution;
    pages: Page;
    users: User;
    'client-accounts': ClientAccount;
    orders: Order;
    packages: Package;
    'webhook-events': WebhookEvent;
    projects: Project;
    tasks: Task;
    sprints: Sprint;
    files: File;
    credentials: Credential;
    timelines: Timeline;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'client-accounts': {
      orders: 'orders';
      projectsJoin: 'projects';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'client-accounts': ClientAccountsSelect<false> | ClientAccountsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    sprints: SprintsSelect<false> | SprintsSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    timelines: TimelinesSelect<false> | TimelinesSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text for accessibility
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    logo?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Client logos and brands for homepage portfolio display
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  /**
   * Client or brand name
   */
  name: string;
  /**
   * Client logo image (preferably transparent PNG)
   */
  logo: string | Media;
  /**
   * Client website URL (optional)
   */
  website?: string | null;
  /**
   * Order in which to display on homepage (lower numbers appear first)
   */
  displayOrder: number;
  /**
   * Feature this client prominently on the homepage
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Consultation booking requests from the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  /**
   * Customer full name
   */
  name: string;
  /**
   * Customer email address
   */
  email: string;
  /**
   * Customer phone number (optional)
   */
  phone?: string | null;
  /**
   * Customer company name (optional)
   */
  company?: string | null;
  /**
   * Service the customer is interested in
   */
  service: 'web-design' | 'ai-automation' | 'custom-software' | 'seo-services' | 'consulting' | 'other';
  /**
   * Project details and customer message
   */
  message: string;
  /**
   * Customer preferred consultation date (optional - for bookings only)
   */
  preferredDate?: string | null;
  /**
   * Customer preferred time (ISO 8601 format, optional - for bookings only)
   */
  preferredTime?: string | null;
  /**
   * Lead status for tracking
   */
  status: 'new' | 'contacted' | 'scheduled' | 'completed' | 'cancelled';
  /**
   * Whether confirmation email was sent
   */
  emailSent?: boolean | null;
  /**
   * Whether calendar event was created
   */
  calendarCreated?: boolean | null;
  /**
   * Google Calendar event link
   */
  calendarEventLink?: string | null;
  /**
   * Internal notes about this lead
   */
  notes?: string | null;
  /**
   * Shopify customer ID (auto-populated)
   */
  shopifyCustomerId?: string | null;
  /**
   * Whether a Shopify password was generated
   */
  shopifyPasswordGenerated?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Category name
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Brief description of this category
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  /**
   * Tag name
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * Post title
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Brief excerpt for SEO and previews (max 200 characters)
   */
  excerpt?: string | null;
  /**
   * Main post content
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Featured image for the post
   */
  featuredImage?: (string | null) | Media;
  /**
   * Post author
   */
  author: string | User;
  /**
   * Primary category for this post
   */
  category?: (string | null) | Category;
  /**
   * Tags for this post
   */
  tags?: (string | Tag)[] | null;
  /**
   * Date when the post was published (auto-set on first publish)
   */
  publishedDate?: string | null;
  /**
   * Estimated read time in minutes
   */
  readTime?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * User full name (not used for client role)
   */
  name?: string | null;
  /**
   * Custom title shown to clients on team views (e.g. "Lead Developer", "UI Designer")
   */
  title?: string | null;
  role: 'admin' | 'user' | 'client';
  /**
   * Client first name
   */
  firstName?: string | null;
  /**
   * Client last name
   */
  lastName?: string | null;
  /**
   * Client company name
   */
  company?: string | null;
  /**
   * Unique username for dashboard access (auto-generated)
   */
  username?: string | null;
  /**
   * Linked client account (auto-created on user creation)
   */
  clientAccount?: (string | null) | ClientAccount;
  /**
   * User workspace identifier
   */
  workspace?: string | null;
  /**
   * 6-digit 2FA verification code (account setup)
   */
  twoFactorCode?: string | null;
  /**
   * Expiry time for 2FA code (account setup)
   */
  twoFactorExpiry?: string | null;
  /**
   * Whether user has verified their account
   */
  twoFactorVerified?: boolean | null;
  /**
   * 6-digit login verification code
   */
  loginTwoFactorCode?: string | null;
  /**
   * Expiry time for login code
   */
  loginTwoFactorExpiry?: string | null;
  /**
   * Show the welcome tips banner in the client portal. Disabled when the client dismisses it.
   */
  showTips?: boolean | null;
  /**
   * Dashboard color preset
   */
  dashboardTheme?: ('void' | 'arctic' | 'ember' | 'emerald' | 'dusk' | 'chrome' | 'light' | 'paper') | null;
  /**
   * Registered WebAuthn passkeys for this user
   */
  passkeyCredentials?:
    | {
        credentialID: string;
        publicKey: string;
        counter: number;
        deviceName?: string | null;
        transports?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        credentialDeviceType?: string | null;
        credentialBackedUp?: boolean | null;
        registeredAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts".
 */
export interface ClientAccount {
  id: string;
  /**
   * Client full name
   */
  name: string;
  /**
   * Client email address
   */
  email?: string | null;
  /**
   * Client first name
   */
  firstName: string;
  /**
   * Client last name
   */
  lastName: string;
  /**
   * Client company name
   */
  company?: string | null;
  /**
   * Client phone number
   */
  phone?: string | null;
  /**
   * Client billing address
   */
  address?: {
    /**
     * Street address
     */
    line1?: string | null;
    /**
     * Suite, unit, etc. (optional)
     */
    line2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * ZIP
     */
    zip?: string | null;
    /**
     * Country
     */
    country?: string | null;
  };
  /**
   * Shopify customer GID (e.g., gid://shopify/Customer/123)
   */
  shopifyCustomerId?: string | null;
  /**
   * Stripe customer ID (e.g., cus_xxxxx) - auto-created on first Stripe order
   */
  stripeCustomerId?: string | null;
  /**
   * Outstanding balance from PENDING orders (what client owes) - auto-updated
   */
  accountBalance?: number | null;
  /**
   * Total number of ALL orders (all statuses) - auto-calculated
   */
  totalOrders?: number | null;
  /**
   * Users responsible for this client account (team members)
   */
  assignedTo?: (string | User)[] | null;
  /**
   * Orders linked to this client account
   */
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Projects linked to this client account
   */
  projectsJoin?: {
    docs?: (string | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * ⚠️ DEPRECATED - Use Projects collection. This data will be migrated.
   */
  projects?:
    | {
        /**
         * Project name
         */
        name: string;
        /**
         * Project status
         */
        status: 'active' | 'on-hold' | 'completed' | 'cancelled';
        /**
         * Project description and notes
         */
        description?: string | null;
        /**
         * Project start date
         */
        startDate?: string | null;
        /**
         * Project end date
         */
        endDate?: string | null;
        /**
         * Project budget (USD)
         */
        budget?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Order number from Stripe (e.g., #1001)
   */
  orderNumber: string;
  /**
   * Current order status
   */
  status: 'pending' | 'paid' | 'cancelled';
  /**
   * Client account for this order
   */
  clientAccount: string | ClientAccount;
  /**
   * Link to project (new relationship field)
   */
  projectRef?: (string | null) | Project;
  /**
   * Project name (DEPRECATED - use projectRef, will be removed after migration)
   */
  project?: string | null;
  /**
   * Order total amount (USD)
   */
  amount: number;
  /**
   * Client balance after this order (audit trail)
   */
  balanceSnapshot?: number | null;
  /**
   * Stripe Invoice ID
   */
  stripeInvoiceId?: string | null;
  /**
   * Stripe hosted invoice URL (sent to customer)
   */
  stripeInvoiceUrl?: string | null;
  /**
   * Stripe Customer ID
   */
  stripeCustomerId?: string | null;
  /**
   * Stripe Payment Intent ID (after payment)
   */
  stripePaymentIntentId?: string | null;
  /**
   * Package this invoice was created from (for deposit/installment tracking)
   */
  packageRef?: (string | null) | Package;
  /**
   * Type of invoice (for deposit/payment plan tracking)
   */
  invoiceType?: ('full' | 'deposit' | 'installment' | 'balance') | null;
  /**
   * Label shown on the Stripe invoice line item (e.g. "50% Deposit")
   */
  invoiceNote?: string | null;
  /**
   * Payment due date (from Stripe invoice or manually set)
   */
  dueDate?: string | null;
  /**
   * Order line items
   */
  lineItems: {
    /**
     * Product or service name
     */
    title: string;
    /**
     * Line item description shown on the invoice
     */
    description?: string | null;
    /**
     * Quantity ordered
     */
    quantity: number;
    /**
     * Price per unit (USD)
     */
    price: number;
    /**
     * Recurring subscription item?
     */
    isRecurring?: boolean | null;
    /**
     * Billing interval
     */
    recurringInterval?: ('month' | 'year') | null;
    /**
     * Stripe Price ID (for subscriptions)
     */
    stripePriceId?: string | null;
    id?: string | null;
  }[];
  /**
   * Invoice email history (audit trail of all sent invoices)
   */
  invoices?:
    | {
        /**
         * When the invoice was sent
         */
        sentAt: string;
        /**
         * Email address invoice was sent to
         */
        sentTo: string;
        /**
         * User who sent the invoice
         */
        sentBy?: (string | null) | User;
        /**
         * Invoice send status
         */
        status: 'sent' | 'failed';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage projects with clients, timelines, and milestones
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * Project name
   */
  name: string;
  /**
   * Current project status
   */
  status: 'pending' | 'in-progress' | 'on-hold' | 'completed' | 'cancelled';
  /**
   * Detailed project description and objectives
   */
  description?: string | null;
  /**
   * Client account for this project
   */
  client: string | ClientAccount;
  /**
   * Team members assigned to this project
   */
  assignedTo?: (string | User)[] | null;
  /**
   * Project start date
   */
  startDate?: string | null;
  /**
   * Expected completion date
   */
  projectedEndDate?: string | null;
  /**
   * Actual completion date (when status = completed)
   */
  actualEndDate?: string | null;
  /**
   * Project milestones and key deliverables
   */
  milestones?:
    | {
        /**
         * Milestone title
         */
        title: string;
        /**
         * Milestone target date
         */
        date: string;
        /**
         * Mark as complete
         */
        completed?: boolean | null;
        /**
         * Milestone details and deliverables
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Total project budget
   */
  budgetAmount?: number | null;
  /**
   * Budget currency
   */
  currency?: ('USD' | 'EUR' | 'GBP') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Shown above line items in the proposal PDF
   */
  coverMessage?: string | null;
  /**
   * Internal / contextual notes (also shown in PDF)
   */
  notes?: string | null;
  /**
   * Template: reusable library item. Proposal: frozen snapshot assigned to a client.
   */
  type: 'template' | 'proposal';
  status: 'draft' | 'sent' | 'accepted' | 'archived';
  /**
   * Client this proposal is assigned to (proposals only)
   */
  clientAccount?: (string | null) | ClientAccount;
  /**
   * Template this proposal was created from
   */
  sourcePackage?: (string | null) | Package;
  /**
   * Project this proposal is linked to
   */
  projectRef?: (string | null) | Project;
  /**
   * Add-on items requested by the client via their portal
   */
  requestedItems?:
    | {
        name: string;
        requestedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Planned payment schedule — entries are invoiced individually when ready
   */
  paymentSchedule?:
    | {
        /**
         * e.g. Deposit, Installment 1, Final Payment
         */
        label: string;
        /**
         * Dollar amount for this payment
         */
        amount: number;
        /**
         * When this payment is due
         */
        dueDate?: string | null;
        /**
         * Set when invoiced — links to the Order record
         */
        orderId?: string | null;
        /**
         * When the invoice was sent
         */
        invoicedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  lineItems?:
    | {
        name: string;
        description?: string | null;
        /**
         * Base price per unit (USD)
         */
        price: number;
        /**
         * Override price shown on proposals (optional — leave blank to use base price)
         */
        adjustedPrice?: number | null;
        quantity?: number | null;
        /**
         * Recurring subscription item?
         */
        isRecurring?: boolean | null;
        /**
         * Billing interval
         */
        recurringInterval?: ('month' | 'year') | null;
        /**
         * Stripe Price ID (optional)
         */
        stripePriceId?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SEO-driven solution pages with flexible content blocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: string;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Short summary shown on the solutions listing page
   */
  description?: string | null;
  /**
   * Add content blocks to build the page
   */
  layout?: ArticleBlock[] | null;
  meta?: {
    /**
     * Overrides page title in search results (50–60 chars recommended)
     */
    title?: string | null;
    /**
     * Shown in search results (150–160 chars recommended)
     */
    description?: string | null;
    /**
     * Open Graph image for social sharing
     */
    image?: (string | null) | Media;
    /**
     * Prevent search engines from indexing this page
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleBlock".
 */
export interface ArticleBlock {
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'article';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL slug. Use "home" for the homepage.
   */
  slug: string;
  layout?: (HeroBlock | CapabilitiesBlock | CtaBlock | ContactFormBlock | OrcaclubCarouselBlock)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Short tagline shown below the greeting
   */
  subheading?: string | null;
  /**
   * Label for the primary CTA button
   */
  primaryButtonLabel?: string | null;
  /**
   * URL for the primary CTA button
   */
  primaryButtonHref?: string | null;
  /**
   * Label for the secondary CTA button
   */
  secondaryButtonLabel?: string | null;
  /**
   * URL for the secondary CTA button
   */
  secondaryButtonHref?: string | null;
  /**
   * Whether to show the client logo marquee at the bottom of the hero
   */
  showClientsCarousel?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilitiesBlock".
 */
export interface CapabilitiesBlock {
  /**
   * Small eyebrow label above the heading
   */
  label?: string | null;
  /**
   * Section heading. "solutions" renders as gradient text in the renderer.
   */
  heading?: string | null;
  /**
   * Descriptive paragraph below the heading
   */
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'capabilities';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * Small eyebrow label above the heading
   */
  label?: string | null;
  /**
   * Section heading
   */
  heading?: string | null;
  /**
   * Descriptive paragraph below the heading
   */
  subheading?: string | null;
  /**
   * Label for the primary CTA button
   */
  primaryButtonLabel?: string | null;
  /**
   * URL for the primary CTA button
   */
  primaryButtonHref?: string | null;
  /**
   * Label for the secondary CTA button
   */
  secondaryButtonLabel?: string | null;
  /**
   * URL for the secondary CTA button
   */
  secondaryButtonHref?: string | null;
  /**
   * Small tagline shown below the buttons
   */
  tagline?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  /**
   * Large gothic heading on the left panel.
   */
  heading?: string | null;
  /**
   * Small uppercase label at the bottom-left of the panel.
   */
  tagline?: string | null;
  contactEmail?: string | null;
  contactLocation?: string | null;
  contactPhone?: string | null;
  step1Title?: string | null;
  step1Sub?: string | null;
  step2Title?: string | null;
  step2Sub?: string | null;
  step3Title?: string | null;
  step3Sub?: string | null;
  /**
   * The clickable service pills on step 2. Value is sent to the API.
   */
  services?:
    | {
        /**
         * Displayed label
         */
        label: string;
        /**
         * URL-safe identifier (e.g. web-design)
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show the "Book a Call" option in step 3. Disable to make "Send a Message" the only option.
   */
  showBookingOption?: boolean | null;
  footerLinkLabel?: string | null;
  footerLinkHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrcaclubCarouselBlock".
 */
export interface OrcaclubCarouselBlock {
  /**
   * Small uppercase label displayed above the carousel.
   */
  sectionLabel?: string | null;
  autoPlay?: boolean | null;
  /**
   * Milliseconds between auto-advances (minimum 2000).
   */
  autoPlayInterval?: number | null;
  /**
   * Add slides for events, news, merchandise drops, and announcements.
   */
  slides: {
    /**
     * Horizontal = wide cinematic card. Vertical = centered portrait card (best for product shots, posters).
     */
    layout: 'horizontal' | 'vertical';
    category: 'event' | 'news' | 'merchandise' | 'announcement';
    /**
     * First image is the primary slide image. Additional images appear in the gallery grid.
     */
    images: {
      image: string | Media;
      /**
       * Optional caption shown on hover in the gallery grid.
       */
      caption?: string | null;
      id?: string | null;
    }[];
    /**
     * Small label above title — e.g. "Limited Drop", "March 2026".
     */
    eyebrow?: string | null;
    /**
     * Main headline. 3–6 words for maximum impact.
     */
    title: string;
    /**
     * Supporting copy beneath the title. 1–2 sentences.
     */
    subtitle?: string | null;
    /**
     * Button label — e.g. "Shop Now", "Learn More", "Register".
     */
    ctaLabel?: string | null;
    /**
     * URL the CTA button links to.
     */
    ctaHref?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'orcaclubCarousel';
}
/**
 * Tracks processed Stripe webhook events
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: string;
  /**
   * Stripe event ID (e.g., evt_xxx)
   */
  eventId: string;
  /**
   * Type of Stripe event (e.g., invoice.paid)
   */
  eventType: string;
  status: 'processing' | 'processed' | 'failed';
  /**
   * PayloadCMS Order ID if applicable
   */
  orderId?: string | null;
  /**
   * Stripe Invoice ID
   */
  stripeInvoiceId?: string | null;
  /**
   * Full event payload from Stripe
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error message if processing failed
   */
  errorMessage?: string | null;
  processingStartedAt?: string | null;
  processingCompletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage tasks within projects with status, priority, and time tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  /**
   * Task title or summary
   */
  title: string;
  /**
   * Detailed task description with formatting
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Current task status
   */
  status: 'pending' | 'in-progress' | 'completed' | 'cancelled';
  /**
   * Task priority level
   */
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  /**
   * Project this task belongs to
   */
  project: string | Project;
  /**
   * User assigned to this task
   */
  assignedTo: string | User;
  /**
   * Optional: Sprint this task is part of
   */
  sprint?: (string | null) | Sprint;
  /**
   * When this task is due
   */
  dueDate?: string | null;
  /**
   * When this task was completed (auto-set)
   */
  completedAt?: string | null;
  /**
   * Estimated hours to complete
   */
  estimatedHours?: number | null;
  /**
   * Actual hours spent on task
   */
  actualHours?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage project sprints with tasks and timeframes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sprints".
 */
export interface Sprint {
  id: string;
  /**
   * Sprint name (e.g., "Sprint 1", "Q1 2026")
   */
  name: string;
  /**
   * Sprint description and objectives
   */
  description?: string | null;
  /**
   * Project this sprint belongs to
   */
  project: string | Project;
  /**
   * Current sprint status
   */
  status: 'pending' | 'in-progress' | 'delayed' | 'finished';
  /**
   * Sprint start date
   */
  startDate?: string | null;
  /**
   * Sprint end date (leave blank for ongoing sprints)
   */
  endDate?: string | null;
  /**
   * What should be accomplished in this sprint
   */
  goalDescription?: string | null;
  /**
   * Running notes and observations for this sprint
   */
  notes?:
    | {
        /**
         * Note content
         */
        text: string;
        /**
         * Auto-set when the note is created
         */
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tasks included in this sprint
   */
  tasks?: (string | Task)[] | null;
  /**
   * Number of completed tasks (auto-calculated)
   */
  completedTasksCount?: number | null;
  /**
   * Total number of tasks (auto-calculated)
   */
  totalTasksCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage documents and files linked to projects and sprints
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: string;
  /**
   * File or document name (auto-populated from filename if not provided)
   */
  name: string;
  /**
   * Type of file
   */
  fileType?: ('document' | 'image' | 'spreadsheet' | 'presentation' | 'pdf' | 'other') | null;
  /**
   * Description of the file contents or purpose
   */
  description?: string | null;
  /**
   * Upload a file or document (optional for generated documents)
   */
  file?: (string | null) | Media;
  /**
   * Template type for generated documents
   */
  documentTemplate?: ('nda' | 'sow') | null;
  /**
   * Branding used when document was generated
   */
  documentBrand?: ('personal' | 'orcaclub') | null;
  /**
   * Stored form data for regenerating this document
   */
  documentData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Project this file belongs to (optional)
   */
  project?: (string | null) | Project;
  /**
   * Sprint this file is a deliverable for (optional)
   */
  sprint?: (string | null) | Sprint;
  /**
   * Version number (e.g., "1.0", "2.1")
   */
  version?: string | null;
  /**
   * Tags for organization (e.g., "contract", "design", "invoice")
   */
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Secure per-project credentials with passwords and secrets encrypted at rest
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: string;
  /**
   * Credential label (e.g. "WordPress Admin", "AWS Console")
   */
  title: string;
  /**
   * Project this credential belongs to
   */
  project: string | Project;
  /**
   * Login URL or service homepage
   */
  website?: string | null;
  /**
   * Username or email address
   */
  username?: string | null;
  /**
   * Password (encrypted at rest using AES-256-GCM)
   */
  password?: string | null;
  /**
   * Additional key/value secrets (API keys, tokens, environment variables)
   */
  secrets?:
    | {
        /**
         * Secret name (e.g. "API_KEY", "Secret Token")
         */
        key: string;
        /**
         * Secret value (encrypted at rest)
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Interactive horizontal timeline pages for project roadmaps
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timelines".
 */
export interface Timeline {
  id: string;
  /**
   * Small label above the title (e.g. "Kawai Digital · Site Relaunch")
   */
  eyebrow: string;
  /**
   * Main heading (e.g. "Launch")
   */
  title: string;
  /**
   * Italic gold word appended to title (e.g. "Roadmap")
   */
  titleEmphasis?: string | null;
  /**
   * Header meta date span (e.g. "March 2 – April 2026")
   */
  dateRange?: string | null;
  /**
   * Second line of header meta (e.g. "Internal Planning Doc")
   */
  metaLabel?: string | null;
  /**
   * Controls the visual presentation of the public timeline page
   */
  style?: ('cinematic' | 'vertical-clean' | 'blueprint' | 'editorial' | 'terminal') | null;
  /**
   * Optional. If set, visitors must enter this code to view the timeline at /orcaclub/projects/[slug].
   */
  accessCode?: string | null;
  /**
   * URL path — auto-generated from title (e.g. "kawai-launch")
   */
  slug: string;
  /**
   * Add phase cards, checklist blocks, or a launch block in order
   */
  phases?:
    | (
        | {
            /**
             * e.g. "Mar 2 – 6"
             */
            dateRange: string;
            /**
             * e.g. "Setup", "Integrate", "Pre-Launch"
             */
            tag?: string | null;
            tagColor?: ('build' | 'integrate' | 'touchup' | 'prep') | null;
            title: string;
            /**
             * Bullet points inside the card
             */
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Highlighted callout at the bottom of the card
             */
            dealerPill?: {
              enabled?: boolean | null;
              /**
               * e.g. "End of week — Soft launch to select dealers for testing"
               */
              text?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'phase';
          }
        | {
            /**
             * Badge text above the node (e.g. "Pre-Launch Checklist")
             */
            dateLabel?: string | null;
            tag?: string | null;
            /**
             * e.g. "Launch Requirements"
             */
            title: string;
            items?:
              | {
                  text: string;
                  /**
                   * Small warning shown below the item text
                   */
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklist';
          }
        | {
            /**
             * Badge above the pulsing node
             */
            dateLabel?: string | null;
            label?: string | null;
            /**
             * Non-italic part (e.g. "Site")
             */
            title?: string | null;
            titleEmphasis?: string | null;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'launch';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'solutions';
        value: string | Solution;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'client-accounts';
        value: string | ClientAccount;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'packages';
        value: string | Package;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: string | WebhookEvent;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'tasks';
        value: string | Task;
      } | null)
    | ({
        relationTo: 'sprints';
        value: string | Sprint;
      } | null)
    | ({
        relationTo: 'files';
        value: string | File;
      } | null)
    | ({
        relationTo: 'credentials';
        value: string | Credential;
      } | null)
    | ({
        relationTo: 'timelines';
        value: string | Timeline;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        logo?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  displayOrder?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  service?: T;
  message?: T;
  preferredDate?: T;
  preferredTime?: T;
  status?: T;
  emailSent?: T;
  calendarCreated?: T;
  calendarEventLink?: T;
  notes?: T;
  shopifyCustomerId?: T;
  shopifyPasswordGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  category?: T;
  tags?: T;
  publishedDate?: T;
  readTime?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  layout?:
    | T
    | {
        article?: T | ArticleBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleBlock_select".
 */
export interface ArticleBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        capabilities?: T | CapabilitiesBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        contactForm?: T | ContactFormBlockSelect<T>;
        orcaclubCarousel?: T | OrcaclubCarouselBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  subheading?: T;
  primaryButtonLabel?: T;
  primaryButtonHref?: T;
  secondaryButtonLabel?: T;
  secondaryButtonHref?: T;
  showClientsCarousel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CapabilitiesBlock_select".
 */
export interface CapabilitiesBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  subheading?: T;
  primaryButtonLabel?: T;
  primaryButtonHref?: T;
  secondaryButtonLabel?: T;
  secondaryButtonHref?: T;
  tagline?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  heading?: T;
  tagline?: T;
  contactEmail?: T;
  contactLocation?: T;
  contactPhone?: T;
  step1Title?: T;
  step1Sub?: T;
  step2Title?: T;
  step2Sub?: T;
  step3Title?: T;
  step3Sub?: T;
  services?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  showBookingOption?: T;
  footerLinkLabel?: T;
  footerLinkHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrcaclubCarouselBlock_select".
 */
export interface OrcaclubCarouselBlockSelect<T extends boolean = true> {
  sectionLabel?: T;
  autoPlay?: T;
  autoPlayInterval?: T;
  slides?:
    | T
    | {
        layout?: T;
        category?: T;
        images?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  role?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  username?: T;
  clientAccount?: T;
  workspace?: T;
  twoFactorCode?: T;
  twoFactorExpiry?: T;
  twoFactorVerified?: T;
  loginTwoFactorCode?: T;
  loginTwoFactorExpiry?: T;
  showTips?: T;
  dashboardTheme?: T;
  passkeyCredentials?:
    | T
    | {
        credentialID?: T;
        publicKey?: T;
        counter?: T;
        deviceName?: T;
        transports?: T;
        credentialDeviceType?: T;
        credentialBackedUp?: T;
        registeredAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts_select".
 */
export interface ClientAccountsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  phone?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
      };
  shopifyCustomerId?: T;
  stripeCustomerId?: T;
  accountBalance?: T;
  totalOrders?: T;
  assignedTo?: T;
  orders?: T;
  projectsJoin?: T;
  projects?:
    | T
    | {
        name?: T;
        status?: T;
        description?: T;
        startDate?: T;
        endDate?: T;
        budget?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  clientAccount?: T;
  projectRef?: T;
  project?: T;
  amount?: T;
  balanceSnapshot?: T;
  stripeInvoiceId?: T;
  stripeInvoiceUrl?: T;
  stripeCustomerId?: T;
  stripePaymentIntentId?: T;
  packageRef?: T;
  invoiceType?: T;
  invoiceNote?: T;
  dueDate?: T;
  lineItems?:
    | T
    | {
        title?: T;
        description?: T;
        quantity?: T;
        price?: T;
        isRecurring?: T;
        recurringInterval?: T;
        stripePriceId?: T;
        id?: T;
      };
  invoices?:
    | T
    | {
        sentAt?: T;
        sentTo?: T;
        sentBy?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  coverMessage?: T;
  notes?: T;
  type?: T;
  status?: T;
  clientAccount?: T;
  sourcePackage?: T;
  projectRef?: T;
  requestedItems?:
    | T
    | {
        name?: T;
        requestedAt?: T;
        id?: T;
      };
  paymentSchedule?:
    | T
    | {
        label?: T;
        amount?: T;
        dueDate?: T;
        orderId?: T;
        invoicedAt?: T;
        id?: T;
      };
  lineItems?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        adjustedPrice?: T;
        quantity?: T;
        isRecurring?: T;
        recurringInterval?: T;
        stripePriceId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  eventId?: T;
  eventType?: T;
  status?: T;
  orderId?: T;
  stripeInvoiceId?: T;
  payload?: T;
  errorMessage?: T;
  processingStartedAt?: T;
  processingCompletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  description?: T;
  client?: T;
  assignedTo?: T;
  startDate?: T;
  projectedEndDate?: T;
  actualEndDate?: T;
  milestones?:
    | T
    | {
        title?: T;
        date?: T;
        completed?: T;
        description?: T;
        id?: T;
      };
  budgetAmount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  priority?: T;
  project?: T;
  assignedTo?: T;
  sprint?: T;
  dueDate?: T;
  completedAt?: T;
  estimatedHours?: T;
  actualHours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sprints_select".
 */
export interface SprintsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  project?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  goalDescription?: T;
  notes?:
    | T
    | {
        text?: T;
        createdAt?: T;
        id?: T;
      };
  tasks?: T;
  completedTasksCount?: T;
  totalTasksCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  name?: T;
  fileType?: T;
  description?: T;
  file?: T;
  documentTemplate?: T;
  documentBrand?: T;
  documentData?: T;
  project?: T;
  sprint?: T;
  version?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  website?: T;
  username?: T;
  password?: T;
  secrets?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timelines_select".
 */
export interface TimelinesSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleEmphasis?: T;
  dateRange?: T;
  metaLabel?: T;
  style?: T;
  accessCode?: T;
  slug?: T;
  phases?:
    | T
    | {
        phase?:
          | T
          | {
              dateRange?: T;
              tag?: T;
              tagColor?: T;
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              dealerPill?:
                | T
                | {
                    enabled?: T;
                    text?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              dateLabel?: T;
              tag?: T;
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        launch?:
          | T
          | {
              dateLabel?: T;
              label?: T;
              title?: T;
              titleEmphasis?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: string | Post;
    } | null;
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}